import Head from 'next/head'
import IncDec from '../components/incDec';
import NewCheckComponent from '../components/NewCheckComponent';
import ShowSelectedCat from '../components/ShowSelectedCat';
export default function Home() {

  return (
    <div >
      <Head>
        <title>Next Redux Tool Tik</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='main-div'>
        <IncDec />
        <NewCheckComponent/>
        <hr />
        <ShowSelectedCat />
      </div>

    </div>
  )
}
